version:  "3"
services:

  db:
    build: mysql
    env_file: .env
    domainname: vcl.local
    hostname: db
    image: "${REGISTRY_HOST}/${NAME}-db"

  www:
    build: www
    env_file: .env
    volumes:
      - /var/log/apache2
      - /var/www/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:db
    depends_on:
      - db
    domainname: vcl.local
    hostname: www
    image: "${REGISTRY_HOST}/${NAME}-www"

  managementnode:
    build: mgmt
    env_file: .env
    domainname: vcl.local
    hostname: mgmt
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - /var/log/vcl/
    image: "${REGISTRY_HOST}/${NAME}-mgmt"

volumes:
  mariadb_data:
